- lib/gvc/gvbuffstderr.c
> Use mktemp instead of mkstemp on Win32

- cmd/tools/gmlscan.l
- lib/cgraph/scan.l
- lib/graph/lexer.c
Similar to fix in commit 99eda42 applied to other places where agerr() was called incorrectly.  See https://github.com/ellson/graphviz/commit/99eda42#commitcomment-11271315 for further discussion.
> Additional agerr() format string fixes

- autogen.sh
On Mac OSX and FreeBSD graphviz_version_date in version.m4 was being set to the empty string since the date command exited with an error.
> Fix version date for Mac OSX and FreeBSD

- lib/vpsc/generate-constraints.cpp
When `scanline.find(v)` finds the first scanline, the tests decrement the iterator *before* the first scanline, which is an invalid position and causes a crash in OS X / iOS libc++. The fix doesn't decrement the iterator if it is already *at* the beginning.
> Fix bad postdecrement of NodeSet iterator

- lib/common/pointset.c
The old code allocates a `pair` then inserts it into a `Dtoset`. However, when the `Dtoset` already has the `pair`, it simply drops the allocated pair. The fix cleans up the `pair` in this case.
> Fix PointSet leak when inserting same point

- macosx/GVWindowController.h
- macosx/GVWindowController.m
Let's say we have a file `a.dot` linking another file `b.dot` using relative URL:
```
digraph a {
"b.dot" [URL="b.dot"];
}
```
Previously, we get the following error message when the node is clicked:
Since it already supports "file://" with absolute paths, I think it makes sense to support the relative ones as well. This patch fixes this error by using the URL of the opened file as a base URL of the target URL.
> Allow relative URL in Graphviz.app

- doc/Dot.ref
It seems that dot indeed provides the (optional) spline start point before the (optional) spline end point. The documentation however lists them in the inverse order, which should be adjusted.
> Update splineType grammar in Dot.ref

- autogen.sh
- configure.ac
While working on the Appveyor build, I noticed some areas in the build files that could be improved. In this pull request I address a few of these:
- I refactored the `GRAPHVIZ_VERSION_DATE` if statement in autogen.sh. I think the code is more elegant, while keeping the result unchanged.
- `graphviz_version_commit `was set to unkown, it is now set to the abbreviated
hash of last commit.
- `graphviz_collection` is now set to `development` instead of `test`, as configure.ac contains a comments saying it is either `stable` or `development`.
> Small changes in autogen.sh and configure.ac

- .travis.yml
With this configuration, Travis will build and release the package to Github when a Git tag is pushed. Right now it publishes to my personal fork, as my encrypted api key is used. This should be changed to the Graphviz repository api key as soon as possible. The [Travis documentation](https://docs.travis-ci.com/user/deployment/releases/) explains how to generate secure api keys for Travis easily and I am willing to help.
> Publishing Linux release to Github with Travis

- lib/cdt/cdt.h
- lib/cdt/dthdr.h
- windows/include/ast_common.h
When compiling with all warnings on Windows, various "'MACRO_NAME is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'" warnings where thrown. This pull request fixes those warnings by placing defined() around the macro names.
> Fixed undefined macro warnings in CDT.

- README.md
Point README reference to tracker to the github tracker instead.
> Changed README.md tracker to reference github. Addresses #97

- cmd/tools/bcomps.vcxproj
- cmd/tools/gvpack.vcxproj
- cmd/tools/mm2gv.vcxproj
- cmd/tools/sccmap.vcxproj
- cmd/tools/tred.vcxproj
- cmd/tools/unflatten.vcxproj
- plugin/core/gvplugin_core.c
- windows/include/ast_common.h
- A few misplaced `defined()` in ast_commmon.h in windows/include caused errors for the Windows build. Removing them solved the problem.
- The recently added mp_types also caused errors on Windows, so I disabled it for now on Windows by using `!defined(WIN32)` around the definitions. Not sure what should be done for this to work.
- A few changes in the project files that allow for a parallel build.
> Fix windows build

- plugin/core/gvrender_core_mp.c
a simple quickfix, that makes the metapost driver ready to debug.
Why does the metapost driver uses fig, but writing a metpost directly?
> quickfix for metapost

- ast_common.h.in
- cmd/lefty/dot2l/dotparse.y
- cmd/smyrna/gui/toolboxcallbacks.h
- configure.ac
- lib/agraph/agraph.h
- lib/cdt/cdt.h
- lib/cgraph/cgraph.h
- lib/cgraph/io.c
- lib/cgraph/mem.c
- lib/graph/graph.h
- lib/graph/libgraph.h
- lib/neatogen/matinv.c
- lib/pathplan/route.c
- lib/pathplan/shortest.c
- lib/sfio/sfcvt.c
- lib/sfio/sfhdr.h
- lib/sfio/sfio.h
- lib/sfio/sfmode.c
- lib/sfio/sfpkrd.c
- lib/sfio/sfpopen.c
- lib/sfio/sfputd.c
- lib/sfio/sftable.c
- lib/sfio/sftmp.c
- lib/sfio/sfvprintf.c
- lib/sfio/sfvscanf.c
- lib/sfio/vthread.h
- lib/vmalloc/malloc.c
- lib/vmalloc/vmalloc.h
- lib/vmalloc/vmexit.c
- lib/vmalloc/vmhdr.h
As discussed in #1139, using C99 enables the use of some newer language features that allow more elegant and more readable code. All major compiler support this standard, even Microsoft's MSVC compiler.
Using C99 results in more compiler warnings when using GCC, because more warnings are enabled by default. Compiler warnings are a good thing and they help to increase the quality of the code, so I created a set of compiler warnings and added this to the the `CFLAGS` in configure.ac. I included a check to only use this configuration when using GCC, because that is the only compiler I tested with and the configure script checks for more compilers.
Using these warning flags, around 14000 warning were generated. This PR also includes some changes that solves around 5500 of those, so about 8500 …
> Enable C99, enable more warnings and solve some warnings.

- .travis.yml
Because the results of `make install` when using a prefix aren't binaries suitable to be released, some build steps could either be removed or simplified. Also added colorgcc to Travis to increase readability of the build log.
Every commit will still result in a new untagged release on Github, but the results of `make dist` will now be attached to these releases. The [Neovim project](https://github.com/neovim/neovim) has a script they use to create nightly releases on every successful build, that aren't untagged releases and only keeps the most recent version. The script can be found [here](https://github.com/neovim/bot-ci/blob/master/ci/nightly.sh). We might be able to incorporate this into our own Travis configuration.
> Improve Travis + deploy make dist results

- configure.ac
With the new way of enabling C99 (`AC_PROG_CC_C99` instead of `-std=c99`) this flag is no longer needed for a successfull compilation.
> Removed POSIX version flag from configure.ac

- doc/info/shapes.html
```graphviz
digraph G {
rankdir=BT
a--b
}
```
```graphviz
digraph G {
rankdir=BT
a--b
}
```
> fix typo TB->BT in docs:shapes

- lib/cgraph/agxbuf.c
- lib/cgraph/attr.c
- lib/cgraph/grammar.y
- lib/cgraph/rec.c
- lib/common/arrows.c
- lib/common/colxlate.c
- lib/common/htmllex.c
- lib/common/htmltable.c
- lib/common/labels.c
- lib/pathplan/cvt.c
- tclpkg/tclpathplan/tclpathplan.c
Some small changes that resolve some `Wconversion` and `-Wsign-conversion` warnings. None of the changes should have effect on the behavior of the code and the program.
The warning reduction counts given in some commits were on my own machine and may not be completely accurate. On Travis there are now 58 warnings less.
> Resolve some conversion warnings

- .travis.yml
- ci/build_and_test.sh
- ci/centos7/Dockerfile
- cmd/edgepaint/Makefile.am
- cmd/mingle/Makefile.am
- plugin/gdiplus/Makefile.am
We recently discussed to whether is was possible for Travis to provide other build platforms like CentOS and Fedora. Travis itself doesn't provide CentOS or Fedora images, but it's possible to use Docker in a Travis build. I don't know how familiar you are with Docker, but it's a tool that provides visualization using containers. It can run a variety of images, including vanilla CentOS (version 5 to 7) and Fedora (version 20 to 24). I'm not sure if it's possible to have multiple architectures as well.
This pull request adds, in addition to the normal build that is still in place, a second build on a CentOS 7 image. It should be easy to add additional images and version, but this will increase the Travis build time.
While getting this to work, I removed the `-lstdc++` flag in some …
> Add build on CentOS 7 to Travis

- lib/gvc/gvrender.c
I saw John working on this and had a look at it as well. `bsearch` is used in this function to find a string in a string array. It's not needed to pass the address of `tok` to the function, because `tok` is already a pointer. `gvrender_comparestr` should then cast the values to `(const char)` instead of `*(char**)`, because `s1` and `s2` are strings, not pointers to a string. With this change the function only calls `strcmp`, so passing `strcmp` to `bsearch` has the same effect and `gvrender_comparestr` can be removed.
This gets rid of all the `-Wcast-qual` warnings.
> Use `strcmp` in instead of `gvrender_comparestr`.

- appveyor.yml
- contrib/diffimg/diffimg.vcxproj
- plugin/gd/gvplugin_gd.vcxproj
Change the build directory of libgd to `build` instead of `gdbuild`, because `build` is ignored by the libgd's .gitignore file. The vcxproject files have been updated to reflect this change.
Changed the download link for freetype because the original link was changed and no longer valid. This caused failing Appveyor builds.
> Appveyor: update libgd dependencies and build dir

- .travis.yml
- ChangeLog
Instead of publishing a new release with an "untagged" name on every
Travis build, this configuration will deploy all these nightlies to a
special "Nightly" release tag.
> Enhanced Travis Nightly Release

- Makefile.am
According to POSIX, '|' only works as an alternation character in grep
when it is extended regular expression mode (egrep, or grep -E).
This is not an issue most of the time because GNU grep accepts it in
non-extended expressions as well, but other grep implementations
adhering to the standard will fail to match the pattern used to generate
graphviz_version.h.
Switching to EGREP (which also requires not escaping the '|'s) makes it
work for all implementations.
> build: Use EGREP to generate graphviz_version.h

- cmd/smyrna/smyrna.vcxproj
- plugin/pango/gvplugin_pango.vcxproj
Outputs like 'png' didn't render the text properly on Windows (rectangles
instead of letters). The cause was that Pango was missings its modules. This
change adds post build commands to the `smyrna` en `gvplugin_pango` Visual
Studio projects, so the required modules are copied and then recognized by
pango.
Fixes issue #1186
> Fix font errors on Windows with binary outputs

- .gitattributes
- doc/winbuild.html
- lib/cgraph/cgraph.def
- lib/cgraph/cgraph.vcxproj
This PR fixes three issues for windows.
- Add missing `agissimple` function to `cgraph.def`
- Fix "attr_widgets.dot is not a Word Document." error while diffing
- Fix the `flex` build command also in the Release Configuration. (My previous PR only fixed it for the Debug Configuration).
> Fix a few windows issues

- doc/winbuild.html
This adds the build instructions provided by Erwin Janssen to the winbuild document, that other users may be able to find it as well.
I'm not sure if this will immediately update the page on github.io, that depends on the settings of this repository as far as I know.
> Add newer build instructions to winbuild.html.

- doc/html/winbuild.html
Manually building `libgd` is no longer needed, this has been removed from the build steps in `winbuild.html`.
> Update winbuild.html to reflect build changes

- doc/infosrc/attrs
- lib/common/globals.h
- lib/common/htmltable.c
- lib/common/input.c
- lib/common/shapes.c
- lib/common/usershape.h
- lib/gvc/gvcproc.h
- lib/gvc/gvrender.c
I often find myself wanting to use icons to help categorize graphviz nodes in a quick visual fashion, but I typically don't like that the image is centered right in the middle of the node.  I know that I can control image placement somewhat by using HTML inside nodes, with `<IMG>` tags, but I generally don't like how large that makes the individual nodes.
So, this pull request adds in an "imagepos" node attribute which can align node images in one of nine positions, from Top Left to Bottom Right.  It defaults to fully centered, as graphviz does currently.
Two things to note:
1. I wasn't sure how this would interact with `lib/common/htmltable.c`, so for now I just set that file to hardcode the fully-centered option.  It's possible I should be doing something more clever there.
2. My distro …
> Add 'imagepos' node attribute to control image placement

- tclpkg/gv/gv_doc_template.tcl
that gets written to man pages
in order to allow for reproducible builds.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
> Allow to override build date

- lib/gvc.vcxproj
- lib/gvc/CMakeLists.txt
The addition of including `unistd.h` or `compat_unistd.h` in gvplugin.c caused the build to fail on Windows because `compat_unistd.h` could not be found. The compatibility header is located in `lib/ast`, which is now added to the include directories. This resolves the error of the failed build on Windows.
> Add lib/ast to include directories for lib/gvc

- configure.ac
This patch will add an argument '--enable-debug' to configure.ac to compile the C source with the gcc arguments "-g -O0" for gdb.
> add argument --enable-debug to configure.ac for gdb

- README.md
to point to GitLab.
This will help people to find the new repository.
> #1286 Update README.md in MOTHBALLED-graphviz
